# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflows in the `root` directory
    directory: "/"
    # Check the for updates once a week
    schedule:
      interval: "weekly"
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  # Enable version updates for Go modules on supported version branches
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v0.12"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v0.9"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v0.6"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "v0.4"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
